### ISSUE TITLE
Crashing with latest dash release 0.36

### ISSUE THREAD

**Issue by robd003** [GibbsConsulting/django-plotly-dash#111]
After upgrading dash to 0.36 I've been getting this error:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 94, in plotly_direct
    da, app = _locate_daapp(name, slug, da)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 43, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/models.py", line 200, in locate_item
    app = dash_app.as_dash_instance(cache_id=cache_id)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 125, in as_dash_instance
    return self.do_form_dash_instance(cache_id=cache_id)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 161, in do_form_dash_instance
    return self.form_dash_instance(replacements, ndid, base_pathname)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 179, in form_dash_instance
    rd.callback(**cb)(func)
  File "/root/.local/share/virtualenvs/voxsnap-v2-8AAyGoZn/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 407, in callback
    [self._fix_callback_item(x) for x in events])
TypeError: callback() takes from 2 to 4 positional arguments but 5 were given

**Comment by robd003** [comment]
Fixed in this pull request: https://github.com/GibbsConsulting/django-plotly-dash/pull/112

**Comment by GibbsConsulting** [comment]
Thanks very much for reporting this and your PR, which is now merged.
