### ISSUE TITLE
Backend error 500 for SimpleExample demo app

### ISSUE THREAD

**Issue by dwinston** [GibbsConsulting/django-plotly-dash#143]
I think I followed the dev installation instructions:
```bash
# Using miniconda instead of virtualenv, but I doubt this is an issue
conda create -n dpd_dev python=3.6
conda activate dpd_dev

# following relevant ./make_env lines
pip install -r requirements.txt
pip install -r dev_requirements.txt
python setup.py develop

# prepare redis
docker pull redis:4
docker run -p 6379:6379 -d redis

# prepare demo
cd demo
./manage.py migrate
./manage.py shell < configdb.py
./manage.py collectstatic -i "*.py" -i "*.pyc" --noinput --link
./manage.py runserver --nostatic

# I later exited `runserver` to freeze packages those tested
pip install -r frozen_dev.txt
./manage.py runserver --nostatic
```

When I go to http://localhost:8000/demo-one I see the following:

![image](https://user-images.githubusercontent.com/1497854/56446478-c5e27280-62b7-11e9-8e44-c74cdac50e5a.png)

and in the console I see
```bash
Internal Server Error: /django_plotly_dash/app/SimpleExample/_dash-update-component
Traceback (most recent call last):
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/views.py", line 77, in update
    resp = view_func()
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/dash_wrapper.py", line 456, in dispatch
    return self. dispatch_with_args(body, argMap=dict())
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/dash_wrapper.py", line 465, in dispatch_with_args
    target_id = '{}.{}'.format(output['id'], output['property'])
TypeError: string indices must be integers
Internal Server Error: /django_plotly_dash/app/SimpleExample/_dash-update-component
Traceback (most recent call last):
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dwinston/miniconda3/envs/djd_dev/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/views.py", line 77, in update
    resp = view_func()
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/dash_wrapper.py", line 456, in dispatch
    return self. dispatch_with_args(body, argMap=dict())
  File "/Users/dwinston/repos/django-plotly-dash/django_plotly_dash/dash_wrapper.py", line 465, in dispatch_with_args
    target_id = '{}.{}'.format(output['id'], output['property'])
TypeError: string indices must be integers
HTTP GET /django_plotly_dash/app/SimpleExample/_dash-component-suites/dash_core_components/dash_core_components.min.js.map 302 [0.03, 127.0.0.1:51759]
HTTP POST /django_plotly_dash/app/SimpleExample/_dash-update-component 500 [0.08, 127.0.0.1:51757]
HTTP POST /django_plotly_dash/app/SimpleExample/_dash-update-component 500 [0.08, 127.0.0.1:51755]
HTTP GET /static/dash/component/dash_core_components/dash_core_components.min.js.map 304 [0.00, 127.0.0.1:51759]
```

Any advice? It seems that the value of the 'output' key in the `body` argument passed to `django_plotly_dash.dash_wrapper.dispatch_with_args` is a `string` rather than `dict`-like. This is the basic first "hello world" demo, so I'm wondering if I'm installing everything properly.

**Comment by mkhorton** [comment]
I also have this same error, except I didn't use conda, just a plain Python 3.7.0 virtualenv. Tried with both `dash-0.41.0` and `dash-0.39.0`.

My full `pip freeze` is as follows:

```
aioredis==1.2.0
alabaster==0.7.12
argh==0.26.2
asgiref==3.1.2
astroid==2.2.5
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
autobahn==19.3.3
Automat==0.7.0
Babel==2.6.0
bleach==3.1.0
certifi==2019.3.9
channels==2.2.0
channels-redis==2.4.0
chardet==3.0.4
Click==7.0
constantly==15.1.0
coverage==4.5.3
daphne==2.3.0
dash==0.39.0
dash-bootstrap-components==0.4.0
dash-core-components==0.44.0
dash-html-components==0.14.0
dash-renderer==0.20.0
dash-table==3.6.0
decorator==4.4.0
Django==2.1.8
django-bootstrap4==0.0.8
-e git+https://github.com/GibbsConsulting/django-plotly-dash.git@6d359795e5df35269b73238669ec0dd17dacd165#egg=django_plotly_dash
django-redis==4.10.0
docopt==0.6.2
docutils==0.14
dpd-components==0.1.0
dpd-static-support==0.0.2
Flask==1.0.2
Flask-Compress==1.4.0
grip==4.5.2
hiredis==1.0.0
hyperlink==19.0.0
idna==2.8
imagesize==1.1.0
incremental==17.5.0
ipython-genutils==0.2.0
isort==4.3.17
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==3.0.1
jupyter-core==4.4.0
lazy-object-proxy==1.3.1
livereload==2.6.0
Markdown==3.1
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==7.0.0
msgpack==0.6.1
nbformat==4.4.0
numpy==1.16.2
packaging==19.0
pandas==0.24.2
path-and-address==2.0.1
pathtools==0.1.2
pkginfo==1.5.0.1
plotly==3.8.0
pluggy==0.9.0
port-for==0.3.1
py==1.8.0
Pygments==2.3.1
PyHamcrest==1.9.0
pylint==2.3.1
pyparsing==2.4.0
pyrsistent==0.14.11
pytest==4.4.1
pytest-cov==2.6.1
pytest-django==3.4.8
python-coveralls==2.9.1
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1
readme-renderer==24.0
redis==3.2.1
requests==2.21.0
requests-toolbelt==0.9.1
retrying==1.3.3
six==1.12.0
snowballstemmer==1.2.1
Sphinx==2.0.1
sphinx-autobuild==0.7.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
tornado==6.0.2
tqdm==4.31.1
traitlets==4.3.2
twine==1.13.0
Twisted==19.2.0
txaio==18.8.1
typed-ast==1.3.4
urllib3==1.24.2
watchdog==0.9.0
webencodings==0.5.1
Werkzeug==0.15.2
whitenoise==4.1.2
wrapt==1.11.1
zope.interface==4.6.0
```

**Comment by delsim** [comment]
I've also seen this. I think that the response from an underlying (flask?) function has changed.

**Comment by GibbsConsulting** [comment]
#146 should fix this, now pushed as prerelease v0.9.10

**Comment by mkhorton** [comment]
Thank you!

**Comment by delsim** [comment]
@dwinston are you in a position to determine if v0.9.10 fixes this issue?

**Comment by dwinston** [comment]
Fixed! Thanks @delsim !
