### ISSUE TITLE
Error in Dash Wrapper.py dispath_with_args

### ISSUE THREAD

**Issue by dragonrider1024** [GibbsConsulting/django-plotly-dash#145]
I've followed the tutorial to get the "SimpleExample" app on a test site. I encountered the following error"

Internal Server Error: /django_plotly_dash/app/SimpleExample/_dash-update-component
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django_plotly_dash/views.py", line 77, in update
    resp = view_func()
  File "/usr/local/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 456, in dispatch
    return self. dispatch_with_args(body, argMap=dict())
  File "/usr/local/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 465, in dispatch_with_args
    target_id = '{}.{}'.format(output['id'], output['property'])
TypeError: string indices must be integers"

I figured it out it is related to the flask.request.get_json() returning a different format that previous flask versions.
With newest version of flaks, the response is
{'output': 'output-size.children', 'changedPropIds': ['dropdown-color.value'], 'inputs': [{'id': 'dropdown-color', 'property': 'value', 'value': 'red'}, {'id': 'dropdown-size', 'property': 'value', 'value': 'medium'}]}

So to get target_id, we just need output (=response['output']). We don't need to retrieve 'id', as in the input case.

**Comment by GibbsConsulting** [comment]
v0.9.10 (containing PR #146) should have this fix. Thanks for your comments.

**Comment by GibbsConsulting** [comment]
@dragonrider1024 does v0.9.10 solve this problem?

**Comment by dragonrider1024** [comment]
Yes. It's fixed. Thanks.
