### ISSUE TITLE
KeyError: 'SECRET_KEY' from Flask internals

### ISSUE THREAD

**Issue by mdiscenza** [GibbsConsulting/django-plotly-dash#198]
I took parts of the demo app and put them into a larger django project. 

I incorporated all of the config changes to my django project's settings.py but I'm still running into an issue where Flask can't find a secret key.  Stack trace below is from when I try to access `demo_one` page. 

Is there somewhere where I should be setting another secret key outside of my own django settings so that the flask server can find it? I looks like possibly this could be exposed from the `dash_wrapper.PseudoFlask` by putting if from the env into that class so Flask can find it?

Any other ideas that don't involve modifying the source? Is there some way I can store a `SECRET_KEY` in some other config location in the project where Flask will find it?

```
KeyError: 'SECRET_KEY'
ERROR 2019-11-16 21:37:18,717 log 55921 123145468321792 Internal Server Error: /demo/demo-one
Traceback (most recent call last):
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 135, in plotly_class
    da, app = _locate_daapp(name, slug, da)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 43, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/models.py", line 200, in locate_item
    app = dash_app.as_dash_instance(cache_id=cache_id)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 165, in as_dash_instance
    return self.do_form_dash_instance(cache_id=cache_id)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 201, in do_form_dash_instance
    return self.form_dash_instance(replacements, ndid, base_pathname)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 213, in form_dash_instance
    serve_locally=self._serve_locally)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/django_plotly_dash/dash_wrapper.py", line 312, in __init__
    **kwargs)
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/dash/dash.py", line 45, in __init__
    if self.server.secret_key is None:
  File "/Users/michaeldiscenza/.virtualenvs/sl-py-H04qH0hZ/lib/python3.6/site-packages/flask/config.py", line 32, in __get__
    rv = obj.config[self.__name__]
KeyError: 'SECRET_KEY'
[16/Nov/2019 21:37:18] "GET /demo/demo-one HTTP/1.1" 500 227816
```

**Comment by GibbsConsulting** [comment]
It has the look-and-feel of a configuration error, but it is hard to comment further without additional information.
One way forward would be to (try to) run the actual demo within the same virtualenv - this might help to highlight where the problem lies.

**Comment by GibbsConsulting** [comment]
Closing due to inactivity
