### ISSUE TITLE
Handling dash.exceptions.PreventUpdate

### ISSUE THREAD

**Issue by interrogator** [GibbsConsulting/django-plotly-dash#205]
Dash allows the use of this special exception, `dash.exceptions.PreventUpdate`, when no components need updating, even though a callback is triggered.

Because callbacks are triggered on page load, I use this `PreventUpdate` feature quite a bit.

They are raised during this line in `dash_wrapper.py`:

```
res = self.callback_map[target_id]['callback'](*args, **argMap)
```

and never handled. Because they aren't handled, I get a 500, traceback and a bad console log, even though everything is pretty much behaving as expected. It would be nice if you could catch this specific error and return without raising anything, as whenever this is used, it is meant to be there.

I had a look at your code, but I'm not sure where exactly I'd best catch the error, and what I'd return to basically say 'do nothing here, but everything is OK'.

Complete traceback example:

```
Internal Server Error: /resources/app/buzzword/_dash-update-component
Traceback (most recent call last):
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django_plotly_dash/views.py", line 93, in update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 562, in dispatch_with_args
    res = self.callback_map[target_id]['callback'](*args, **argMap)
  File "/home/danny/venv/py3.7/lib/python3.7/site-packages/dash/dash.py", line 1366, in add_context
    raise exceptions.PreventUpdate
dash.exceptions.PreventUpdate
[03/Dec/2019 14:59:44] "POST /resources/app/buzzword/_dash-update-component HTTP/1.1" 500 136760
```

**Comment by GibbsConsulting** [comment]
Thanks for raising this. Added task #205 - it should be a straightforward addition to the codebase.

**Comment by GibbsConsulting** [comment]
@interrogator `PreventUpdate` should now be correctly handled, as of v1.1.2
Are you in a position to try this out?

**Comment by interrogator** [comment]
Confirmed, no errors raised with latest version. Closing!
