### ISSUE TITLE
NameError: name 'state' is not defined

### ISSUE THREAD

**Issue by Pritesh-Inexture** [GibbsConsulting/django-plotly-dash#270]
I have a simple dash app that shows a data table reading from an excel file and there are buttons to change the data and save it.
However, whenever I click on the buttons I get errors and call back does not work.

Here, is the code and traceback

```
    app = DjangoDash(dash_name)

    LOCALFILENAME1 = file_path

    data_cust = pd.read_excel(LOCALFILENAME1, sheet_name='Customer Data')
    data_finance = pd.read_excel(LOCALFILENAME1, sheet_name='Financial Data')
    data_marketing = pd.read_excel(LOCALFILENAME1, sheet_name='Marketing Data')

    def dashTab(df, col_num, tabl_name):
        dt = dash_table.DataTable(
            id=tabl_name,
            columns=[{"name": i, "id": i, "clearable": True} for i in df[:col_num].columns],
            data=df[:col_num].to_dict("rows"), editable=True, row_deletable=True,
            # export_format='xlsx',
            export_format='csv',
            export_headers='display',
            merge_duplicate_headers=True
        )

        return dt

    app.layout = html.Div(id='main-div', children=[

        dcc.Tabs([

            # TAB 1: CUSTOMER
            dcc.Tab(label='Customer', id='tab_cust', children=[

                html.Div(id="div-1", children=[
                    # html.Br(),
                    # html.Br(),
                    # dash_table.DataTable(id='tabl_cust'),
                    dashTab(data_cust, len(data_cust), 'tabl_cust'),
                ]),

                # html.Br(),
                html.Button('Add Row', id='cust-editing-rows-button', n_clicks=0),
                html.Button('Save & Lock', id='cust-save-button', n_clicks=0),
                html.Button('Modify', id='cust-modif-button', n_clicks=0)
            ]),

            # TAB 2: FINANCE
            dcc.Tab(label='Finance', children=[

                html.Br(),
                html.Br(),
                dashTab(data_finance, len(data_finance), 'tabl_fin'),
                html.Br(),
                html.Button('Add Row', id='fin-editing-rows-button', n_clicks=0),
            ]),

            # TAB 3: MARKETING
            dcc.Tab(label='Marketing', children=[
                html.Br(),
                html.Br(),
                dashTab(data_marketing, len(data_marketing), 'tabl_mar'),
                html.Br(),
                html.Button('Add Row', id='mar-editing-rows-button', n_clicks=0),
            ]),

        ])
    ])

    @app.callback(
        # Output('tabl_cust', 'data'),
        # Output('tab_cust','children'),
        Output('div-1', 'children'),
        [Input('cust-save-button', 'n_clicks'),
         Input('cust-editing-rows-button', 'n_clicks')],
        [State('tabl_cust', 'data'),
         State('tabl_cust', 'columns')])
    def updateDataTable(save_nclicks, add_nclicks, data, columns):
        # SAVE BUTTON
        # def saveDataTable(save_nclicks,data):
        print(save_nclicks)
        print(add_nclicks)

        def saveDataTable(data):
            df = pd.DataFrame(data)
            output = df.to_csv(index_label="idx", encoding="utf-8")
            print(output)
            return df

        # ADD ROW BUTTON
        def addRow(data, columns):

            print("add_rows 1:", add_nclicks)
            data.append({c['id']: '' for c in columns})
            print(add_nclicks)
            print(data)
            df = pd.DataFrame(data)
            print(df)
            return df

        print("ADD_CLICKS:", add_nclicks)
        if add_nclicks:
            # if addrow_value != 0:
            # print("add_nclicks:",add_nclicks)
            print("add_nclicks:", add_nclicks)
            table_plus_row = addRow(data, columns)
            tabl_cust = dashTab(table_plus_row, len(table_plus_row), 'tabl_cust'),
            return tabl_cust

        print("SAVE_NCLICKS:", save_nclicks)
        if save_nclicks:
            # if not save_value is None:
            # print("save_nclicks:",save_nclicks)
            print("save_nclicks:", save_nclicks)
            saved_data = saveDataTable(data)
            tabl_cust = dashTab(saved_data, len(saved_data), 'tabl_cust')
            return tabl_cust

        else:
            df = pd.DataFrame(data)
            print(df)
            tabl_cust = dashTab(df, len(df), 'tabl_cust')
            return tabl_cust

        # return tabl_cust

    @app.callback(Output('cust-save-button', 'n_clicks'),
                  [Input('cust-modif-button', 'n_clicks')])
    def save_button_reset(n_clicks):
        # if not n_clicks is None:
        if n_clicks:
            # print("savenclicks:",n_clicks_state)
            return 0

    @app.callback(Output('cust-editing-rows-button', 'n_clicks'),
                  [Input('cust-modif-button', 'n_clicks'),
                   Input('cust-save-button', 'n_clicks')])
    def addrow_button_reset(modif_n_clicks, save_n_clicks):
        # if not n_clicks is None:
        if modif_n_clicks:
            # print("savenclicks:",n_clicks_state)
            return 0

        if save_n_clicks:
            # print("savenclicks:",n_clicks_state)
            return 0

    @app.callback(
        Output('tabl_fin', 'data'),
        [Input('fin-editing-rows-button', 'n_clicks')],
        [State('tabl_fin', 'data'),
         State('tabl_fin', 'columns')])
    def add_row_fin(n_clicks, rows, columns):
        if n_clicks > 0:
            rows.append({c['id']: '' for c in columns})
        return rows

    @app.callback(
        Output('tabl_mar', 'data'),
        [Input('mar-editing-rows-button', 'n_clicks')],
        [State('tabl_mar', 'data'),
         State('tabl_mar', 'columns')])
    def add_row_mar(n_clicks, rows, columns):
        if n_clicks > 0:
            rows.append({c['id']: '' for c in columns})
        return rows

```

```
Internal Server Error: /django_plotly_dash/app/asdf/_dash-update-component
Traceback (most recent call last):
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django_plotly_dash/views.py", line 93, in _update
    resp = view_func()
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 584, in dispatch
    return self.dispatch_with_args(body, argMap=dict())
  File "/media/pritesh/Data/dashfactory/django-dash-env/lib/python3.7/site-packages/django_plotly_dash/dash_wrapper.py", line 653, in dispatch_with_args
    for c in state:
NameError: name 'state' is not defined
[27/Jul/2020 09:56:19] "POST /django_plotly_dash/app/asdf/_dash-update-component HTTP/1.1" 500 119002
```

The data table does get rendered in the browser but it is not able to send the callbacks of button
This app works fine if I run it independently and not with Django.

**EDIT**

I was going through the library code and realised it is maybe just a typo
![image](https://user-images.githubusercontent.com/50139053/88531920-48acbe00-d021-11ea-99c6-57fd84b760e0.png)

If you see this `for c in state` it should be `states` because it is declared as `states` here
![image](https://user-images.githubusercontent.com/50139053/88531989-65e18c80-d021-11ea-95c9-6cad37fa481e.png)

I edited the code and it also solved the bug, my callbacks were working

**Comment by Pritesh-Inexture** [comment]
Closing this as I realised that the bug is solved in version 1.4.2
