### ISSUE TITLE
hi,i get your demo ，then run your demo/manage.gy ,here is the errors,thans

### ISSUE THREAD

**Issue by exist2013** [GibbsConsulting/django-plotly-dash#278]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\code\python\django-plotly-dash\django_plotly_dash\__init__.py", line 31, in <module>
    from .dash_wrapper import DjangoDash
  File "F:\code\python\django-plotly-dash\django_plotly_dash\dash_wrapper.py", line 33, in <module>
    from dash._utils import split_callback_id, inputs_to_dict
ImportError: cannot import name 'split_callback_id' from 'dash._utils' (C:\ProgramData\Anaconda3\envs\env_py_3.7\lib\site-packages\dash\_utils.py)

**Comment by GibbsConsulting** [comment]
That error is saying that `django-plotly-dash` cannot be imported, which in turn suggests that there was a problem with installation.

Did you follow the installation [instructions](https://django-plotly-dash.readthedocs.io/en/latest/installation.html#source-code-and-demo), and did any of the steps generate an error?

**Comment by exist2013** [comment]
![image](https://user-images.githubusercontent.com/6021238/93454807-0eb7b400-f90e-11ea-8987-f278c2c7aba2.png)
I install sucessfully, this picture , my computer is windows 10, windows environment is supported?

**Comment by GibbsConsulting** [comment]
@exist2013 you need to follow the installation instructions in the link above to get the demo to run. Each step is in the form of a shell script containing a number of commands. On windows, you need to perform the equivalent steps by executing (the windows equivalent of) each command.

The demo should work on windows, although no-one has provided the equivalent bat scripts.

**Comment by GibbsConsulting** [comment]
Closing due to inactivity
