### ISSUE TITLE
 How to debug 'Error loading dependencies'

### ISSUE THREAD

**Issue by axru5812** [GibbsConsulting/django-plotly-dash#31]
I've setup the dash app and I've managed to get it to load in the main website but I'm getting the error:
```
Error loading dependencies
```
Is there any method to get information about exactly what error is causing this, such as a logfile or similar? I've tried with several different dash_apps that I know can run on my system and always recieve this message

Thanks!

**Comment by delsim** [comment]
I find that the usual culprit is a lack of static assets. Checking the javascript console and network information in the debugging panel in the browser is often a good first step. Django itself might also provide some logging info, particularly if there is something missing or an issue running code. 

To eliminate some of the mistakes I usually make (invariably not configuring things properly), have you (a) got the latest version of django-plotly-dash and (b) got the demo working?

**Comment by axru5812** [comment]
Thanks! So I managed to find the error messages (I was just a bit blind) but what I'm getting is that Flask is throwing a runtime error:
```
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

This happens both in my own project and when I run the demo

**Comment by delsim** [comment]
Do you know what piece of code is generating this error? If you're in a position to share it, a stack trace, ideally from when running the demo, would be helpful.

**Comment by axru5812** [comment]
Hi 
Really sorry it took so long. I've been gone for a week, but here is the stack trace from trying to run demo1
```
Internal Server Error: /django_plotly_dash/app/SimpleExample_dash-dependencies
Traceback (most recent call last):
  File "/home/axel/anaconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/axel/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/axel/anaconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/axel/anaconda3/lib/python3.6/site-packages/django_plotly_dash/views.py", line 43, in dependencies
    resp = view_func()
  File "/home/axel/anaconda3/lib/python3.6/site-packages/dash/dash.py", line 330, in dependencies
    } for k, v in list(self.callback_map.items())
  File "/home/axel/anaconda3/lib/python3.6/site-packages/flask/json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "/home/axel/anaconda3/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/axel/anaconda3/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/axel/anaconda3/lib/python3.6/site-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.

```

**Comment by stakemura** [comment]
Hi. I faced the same error as shown as following.

- Environment
Windows 10 Enterprise 64bit
Python 3.6 64bit

- Related modules
Django==2.0.2
django-bootstrap4==0.0.6
django-plotly-dash==0.6.0
django-redis==4.9.0
dash==0.24.0
dash-core-components==0.27.1
dash-dangerously-set-inner-html==0.0.1
dash-html-components==0.11.0
dash-renderer==0.13.0

```
System check identified no issues (0 silenced).
August 17, 2018 - 03:47:40
Django version 2.0.2, using settings 'demo.settings'
Starting ASGI/Channels version 2.1.2 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2018-08-17 03:47:40,934 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2018-08-17 03:47:40,935 - INFO - server - Configuring endpoint tcp:port=8000:interface=127.0.0.1
2018-08-17 03:47:40,937 - INFO - server - Listening on TCP address 127.0.0.1:8000
[2018/08/17 03:47:41] HTTP GET / 200 [0.23, 127.0.0.1:59134]
[2018/08/17 03:47:41] HTTP GET /static/demo/logo.svg 404 [0.03, 127.0.0.1:59135]
[2018/08/17 03:47:41] HTTP GET /static/demo/demo.css 304 [0.03, 127.0.0.1:59134]
[2018/08/17 03:47:44] HTTP GET /demo-one 200 [0.04, 127.0.0.1:59135]
[2018/08/17 03:47:44] HTTP GET /static/demo/logo.svg 404 [0.02, 127.0.0.1:59135]
[2018/08/17 03:47:44] HTTP GET /django_plotly_dash/app/SimpleExample 200 [0.03, 127.0.0.1:59135]
[2018/08/17 03:47:45] HTTP GET /django_plotly_dash/app/SimpleExample_dash-layout 200 [0.02, 127.0.0.1:59135]
Internal Server Error: /django_plotly_dash/app/SimpleExample_dash-dependencies
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\django_plotly_dash\views.py", line 43, in dependencies
    resp = view_func()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 495, in dependencies
    } for k, v in list(self.callback_map.items())
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\json.py", line 251, in jsonify
    if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
  File "C:\ProgramData\Anaconda3\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
    return self.__local()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

**Comment by delsim** [comment]
Using python 3.6 and pip install (so the latest versions of each package from pypi) gives me a working demo on Linux Mint 18.1 and also Ubuntu 16.04. Whilst "works for me" isn't particularly helpful, it does suggest that the issue could be due to differences in other packages (eg Flask or friends).

Would it be possible for someone to post a full dump of all the packages in use (ie ``pip freeze`` output or the equivalent to show each package and its version) when observing the error? I don't have access to a Windows environment to test. I will try to get an anaconda one up and running and try that.

**Comment by stakemura** [comment]
As I mentioned before, my environment is as below.
```
Django==2.0.2
django-bootstrap4==0.0.6
django-plotly-dash==0.6.0
django-redis==4.9.0
dash==0.24.0
dash-core-components==0.27.1
dash-html-components==0.11.0
dash-renderer==0.13.0
``` 

Could you inform me your successful version of the required packages?
I will try them.

**Comment by axru5812** [comment]
Based on your comment @delsim I checked my version of flask and realized that it was super old. After ugrading that version to the most recent in the conda channels it works!

Thanks for an awesome plugin, it's going to save me tons of time! 
Is there any way to make the embedded window not scrolling by the way?

**Comment by stakemura** [comment]
@delsim @axru5812 After ugrading Flask, Demo 1,2 works.
Thanks!

**Comment by GibbsConsulting** [comment]
@axru5812 - there is some control at the moment of height of the window relative to width, see the ``ratio`` parameter of the ``plotly_app`` template tag. I've also created #35 to extend this to enable more control, such as absolute sizing.

**Comment by GibbsConsulting** [comment]
It seems that this issue can be cured by adding a minimum version requirement for Flask. At the moment I appear to be using v1.0.2 - at least, that's what the [frozen](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/frozen_dev.txt) values from the last released build report. Unless anyone has a particular need for an older (but still sufficiently new!) version, I will change the requirements to require at least https://github.com/GibbsConsulting/django-plotly-dash/blob/master/frozen_dev.txt1.0.2

**Comment by GibbsConsulting** [comment]
PR #38 fixes this issue and has been merged into trunk. Closing this issue on the assumption that it is now resolved; please re-open if you find things to be otherwise.
