### ISSUE TITLE
Trying to add a second Direct insertion into the demo gives error: Module "demo.scaffold" does not define a "new_view" attribute/class

### ISSUE THREAD

**Issue by gjruppert** [GibbsConsulting/django-plotly-dash#330]
I'm just learning Django/Python so forgive my ignorance.

I am trying to modify the demo project by adding a second direct insertion example.  The demo runs and the original Demo 6 works, but my new app (county-map) throws:
Template error:
In template /Users/Development/demo/demo/templates/base.html, error at line 0
   Module "demo.scaffold" does not define a "county_map_view" attribute/class

Any help is appreciated.

Full error:

Environment:
Request Method: GET
Request URL: http://localhost:8000/county-map

Django Version: 3.1.7
Python Version: 3.9.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'channels',
 'bootstrap4',
 'django_plotly_dash.apps.DjangoPlotlyDashConfig',
 'dpd_static_support']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django_plotly_dash.middleware.BaseMiddleware',
 'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template /Users/Development/demo/demo/templates/base.html, error at line 0
   Module "demo.scaffold" does not define a "county_map_view" attribute/class
   1 : <!DOCTYPE HTML>
   2 : <html>
   3 :  <head>
   4 :    {% load plotly_dash%}
   5 :    {% load static%}
   6 :    {% load bootstrap4%}
   7 :    {% bootstrap_css%}
   8 :    {% bootstrap_javascript jquery="full"%}
   9 :    {% block extra_header%}{% endblock%}
   10 :    {% block app_header_css%}

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 20, in import_string
    return getattr(module, class_name)

The above exception (module 'demo.scaffold' has no attribute 'county_map_view') was the direct cause of the following exception:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.9/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 155, in plotly_class
    da, app = _locate_daapp(name, slug, da)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 43, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/models.py", line 227, in locate_item
    dash_app = find_stateless_by_name(ident)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/models.py", line 84, in find_stateless_by_name
    dash_app = get_stateless_by_name(name)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/models.py", line 40, in get_stateless_by_name
    return get_local_stateless_by_name(name)
  File "/usr/local/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 128, in get_local_stateless_by_name
    sa = _stateless_app_lookup_func(name)
  File "/Users/Development/nrlc_covid19/demo/scaffold.py", line 11, in stateless_app_loader
    return import_string("demo.scaffold." + app_name)
  File "/usr/local/lib/python3.9/site-packages/django/utils/module_loading.py", line 22, in import_string
    raise ImportError('Module "%s" does not define a "%s" attribute/class' % (

Exception Type: ImportError at /county-map
Exception Value: Module "demo.scaffold" does not define a "county_map_view" attribute/class

**Comment by GibbsConsulting** [comment]
@gjruppert your specific problem is that `django-plotly-dash` doesn't know about the dash app called `county_map_view`. You should import the module where this app is defined; usually this can be done from a suitable `urls.py` file - an example in this demo is at about lines 28-31 of [this file](https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/urls.py)

Separately, this also exposes a code path with less than ideal exception handling. I'll create a PR to address that.

**Comment by gjruppert** [comment]
Thank you.  The demo has been enormously helpful.

From: Gibbs Consulting ***@***.***>
Reply-To: GibbsConsulting/django-plotly-dash ***@***.***>
Date: Monday, April 5, 2021 at 8:49 AM
To: GibbsConsulting/django-plotly-dash ***@***.***>
Cc: Gerard Ruppert ***@***.***>, Mention ***@***.***>
Subject: Re: [GibbsConsulting/django-plotly-dash] Trying to add a second Direct insertion into the demo gives error: Module "demo.scaffold" does not define a "new_view" attribute/class (#330)


@gjruppert<https://github.com/gjruppert> your specific problem is that django-plotly-dash doesn't know about the dash app called county_map_view. You should import the module where this app is defined; usually this can be done from a suitable urls.py file - an example in this demo is at about lines 28-31 of this file<https://github.com/GibbsConsulting/django-plotly-dash/blob/master/demo/demo/urls.py>

Separately, this also exposes a code path with less than ideal exception handling. I'll create a PR to address that.

**Comment by gjruppert** [comment]
I've added a new file "state_map.py" which is a copy of county_map.py, I've added "state_map" and "state_map_view" to all the proper places and I still get the: Module "demo.scaffold" does not define a "state_map_view" attribute/class

I got the county_map_view to work by inserting the code into the dash_apps.py, running that added county_map and county_map_view to the Stateless Apps in Admin.   I don't want to try that with the new app until I can figure out that I'm doing incorrectly.

urls.py
# pylint: disable=wrong-import-position,wrong-import-order

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
import demo.dash_apps      # pylint: disable=unused-import
import demo.county_map
import demo.state_map

from django_plotly_dash.views import add_to_session

from .views import state_summary_view, county_map_view, state_map_view, AdminLogin, AdminLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', AdminLogin.as_view(), name="login"),
    path('logout/', AdminLogout.as_view(), name="logout"),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('', TemplateView.as_view(template_name='index.html'), name="home"),
    path('county-map', county_map_view, name="county-map"),
    path('state-map', state_map_view, name="state-map"),
    path('state-summary', state_summary_view, name="state-summary"),

    path('demo-session-var', add_to_session, name="session-variable-example"),    

]
# Add in static routes so daphne can serve files; these should
# be masked eg with nginx for production use

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

**Comment by gjruppert** [comment]
I think I got it.  I had to add the includes to the scaffold.py
...
from demo.dash_apps import state_summary_view, covid19_line_view
from demo.county_map import county_map_view
from demo.state_map import state_map_view
...
