### ISSUE TITLE
Plot does not update when using datashader+holoviews to plot

### ISSUE THREAD

**Issue by Noskario** [GibbsConsulting/django-plotly-dash#365]
I want to integrate a scatterplot into my website. I want it to be zoomable, so I use holoviews, as proposed in the example "Visualizing Large Datasets with Datashader" on https://dash.plotly.com/holoviews

However, after opening the URL, the plot is there but does not update when zooming. My django-console gives
```
Internal Server Error: /django_plotly_dash/app/myPlot1/_dash-update-component
Traceback (most recent call last):
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\dash_wrapper.py", line 698, in dispatch_with_args
    res = callback(*args, **{k: v for k, v in argMap.items() if k in parameters_to_inject})
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\dash\dash.py", line 1010, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\holoviews\plotting\plotly\dash.py", line 498, in update_figure
    triggered_prop_ids = {entry["prop_id"] for entry in callback_context.triggered}
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\dash\_callback_context.py", line 11, in assert_context
    raise exceptions.MissingCallbackContextException(
dash.exceptions.MissingCallbackContextException: dash.callback_context.triggered is only available from a callback!
[15/Nov/2021 18:54:56] "POST /django_plotly_dash/app/myPlot1/_dash-update-component HTTP/1.1" 500 18511
Internal Server Error: /django_plotly_dash/app/myPlot1/_dash-update-component
Traceback (most recent call last):
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\django_plotly_dash\dash_wrapper.py", line 698, in dispatch_with_args
    res = callback(*args, **{k: v for k, v in argMap.items() if k in parameters_to_inject})
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\dash\dash.py", line 1010, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\holoviews\plotting\plotly\dash.py", line 498, in update_figure
    triggered_prop_ids = {entry["prop_id"] for entry in callback_context.triggered}
  File "C:\Users\oskar\PycharmProjects\dash_embed_test\venv\lib\site-packages\dash\_callback_context.py", line 11, in assert_context
    raise exceptions.MissingCallbackContextException(
dash.exceptions.MissingCallbackContextException: dash.callback_context.triggered is only available from a callback!
[15/Nov/2021 18:54:56] "POST /django_plotly_dash/app/myPlot1/_dash-update-component HTTP/1.1" 500 18511
```

Let me give you some information to reproduce the error:

```
bokeh.__version__='2.4.1'
holoviews.__version__='1.14.6'
datashader.__version__='0.13.0'
plotly.__version__='5.3.1'
dash.__version__='1.20.0'
django_plotly_dash.__version__='1.6.6'
django.__version__='3.2.9'
```

`urls.py`:
```
from django.urls import path, include
from . import views

urlpatterns = [
    path('plot1',views.plot1,name='plot1'),
]
```

`views.py`:
```
from django.shortcuts import render
import my_first_dash_plotly_app.my_plot1
def plot1(request):
    return render(request, 'my_first_dash_plotly_app/plot1.html')
```

`my_plot1.py`:
```
import dash
import dash_html_components as html
from plotly.data import iris
import xarray
import datashader
import holoviews as hv
from holoviews.plotting.plotly.dash import to_dash
from holoviews.operation.datashader import datashade,rasterize

import numpy as np
import pandas as pd

from django_plotly_dash import DjangoDash

# Load iris dataset and replicate with noise to create large dataset
df_original = iris()[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
df = pd.concat([
    df_original + np.random.randn(*df_original.shape) * 0.1
    for i in range(10000)
])
dataset = hv.Dataset(df)

scatter = datashade(
    hv.Scatter(dataset, kdims=["sepal_length"], vdims=["sepal_width"])
).opts(title="Datashader with %d points" % len(dataset))

app = DjangoDash('myPlot1')
components = to_dash(
    app, [scatter], reset_button=True
)

app.layout = html.Div(components.children)

```

`plot1.html`:
```
{%load plotly_dash%}

{%plotly_app name="myPlot1"%}
```

Let me know if there is something, that is not clear!

**Comment by GibbsConsulting** [comment]
The `dash.callback_context` variable is some sort of global variable. Not going to comment on the wisdom of using global variables, as there are presumably many considerations that go into such design choices, but the use of this variable is definitely not supported within `django-plotly-dash`. This is most unlikely to change.
