### ISSUE TITLE
Flask Debug issue on deployment

### ISSUE THREAD

**Issue by b-stead** [GibbsConsulting/django-plotly-dash#434]
I have a webapp that worked locally. Having deployed on PythonAnywhere I have encountered an error that I don't know how to resolve.

The error log provides the following
`File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/dash/dash.py", line 494, in __init__
self.init_app()
 File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/dash/dash.py", line 558, in init_app
self.server.before_request(self._setup_server)
File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/scaffold.py", line 39, in wrapper_func
if self._is_setup_finished():
File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/app.py", line 517, in _is_setup_finished
return self.debug and self._got_first_request
File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/app.py", line 792, in debug
return self.config["DEBUG"]
KeyError: 'DEBUG`

The WSGI file in python anywhere is as follows.
```
import os
import sys

path = '/home/TheBoatShed/demo'
if path not in sys.path:
    sys.path.append(path)

os.environ['DJANGO_SETTINGS_MODULE'] = 'demosite.settings'

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()
```

I am self taught mostly and have reached the limit of my knowledge in understanding the backend of the frameworks in play.

The code is available here [https://github.com/b-stead/demo.git](url)

**Comment by GibbsConsulting** [comment]
It is hard to tell even what the content of your wsgi file is - you should at least format it so that others can read it.

In the meantime, are you actually using this wsgi file locally to launch Django and access the dash apps through it without errors? If not, you should focus on getting that working first. If however you are, then you should review whatever PythonAnywhere has to say about using Django and reconcile that with your configuration - in this situation then any errors emitted by either the PythonAnywhere infrastructure or Django would be useful.

**Comment by b-stead** [comment]
Apologies for the formatting. Have edited the original post.

The WSGI file above is from PythonAnywhere. As part of their system they have their own WSGI file that is added in the setup of the website. I have followed their instructions in doing this. During the setup I also followed the Django deployment guidance in setting up my code to work in production.

The WSGI that I have locally is 
```
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'demosite.settings')

application = get_wsgi_application()
```
The general parts of the site that run on Django are working correctly in Deployment. The Dash apps are showing in the Admin site in the stateless apps area. Running locally everything is working on my machine.

On the live site, the error occurs when clicking the link to one of the dash apps. At this stage I then get a 500 error. The error log from PythonAnywhere is below.

```
2022-12-30 13:28:06,182: OK: /visuals/demo1/
Traceback (most recent call last):
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/TheBoatShed/demo/./visuals/views.py", line 12, in demo1
    return render(request, template_name=template_name, context=context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 76, in plotly_app
    da, app = _locate_daapp(name, slug, da, cache_id=cache_id)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/templatetags/plotly_dash.py", line 43, in _locate_daapp
    da, app = DashApp.locate_item(name, stateless=True, cache_id=cache_id)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/models.py", line 231, in locate_item
    app = dash_app.as_dash_instance(cache_id=cache_id)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 227, in as_dash_instance
    return self.do_form_dash_instance(cache_id=cache_id)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 263, in do_form_dash_instance
    return self.form_dash_instance(replacements, ndid, base_pathname)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 271, in form_dash_instance
    rd = WrappedDash(base_pathname=base_pathname,
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/django_plotly_dash/dash_wrapper.py", line 429, in __init__
    super().__init__(__name__, **kwargs)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/dash/dash.py", line 494, in __init__
    self.init_app()
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/dash/dash.py", line 558, in init_app
    self.server.before_request(self._setup_server)
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/scaffold.py", line 39, in wrapper_func
    if self._is_setup_finished():
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/app.py", line 517, in _is_setup_finished
    return self.debug and self._got_first_request
  File "/home/TheBoatShed/.virtualenvs/myenv/lib/python3.9/site-packages/flask/app.py", line 792, in debug
    return self.config["DEBUG"]
KeyError: 'DEBUG'
```

Hopefully this helps to narrow down where the issue lies

**Comment by delsim** [comment]
What versions of django-plotly-dash and dash are you running? This could just be a manifestation of #425 - if so you need to keep the versions compatible. Ideally, recent versions of both.

**Comment by b-stead** [comment]
Thanks D_P_D was behind. updated and running. Thanks
