### ISSUE TITLE
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

### ISSUE THREAD

**Issue by samarthsarin** [GibbsConsulting/django-plotly-dash#472]
I have install the latest version of django_plotly_dash library.
When I add 'django_plotly_dash.apps.DjangoPlotlyDashConfig' in INSTALLED_APPS the following error shows up and my django app doesn't start.

DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Please help me solve this issue.

**Comment by delsim** [comment]
@samarthsarin is there any more to the error message?

In particular, it would be helpful to know what module contains the import statement leading to this warning.

However, a DeprecationWarning is just that - a warning - and on its own would not (usually!) cause program execution to halt.

**Comment by samarthsarin** [comment]
python .\source\manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\ssarin\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\ssarin\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django\apps\config.py", line 178, in create
    mod = import_module(mod_path)
  File "C:\Users\ssarin\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django_plotly_dash\__init__.py", line 31, in <module>
    from .dash_wrapper import DjangoDash
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\django_plotly_dash\dash_wrapper.py", line 33, in <module>
    import dash
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\dash\__init__.py", line 36, in <module>
    from .dash import (  # noqa: F401,E402
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\dash\dash.py", line 22, in <module>
    from pkg_resources import get_distribution, parse_version
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 73, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\Users\ssarin\Anaconda3\lib\site-packages\win32\lib\pywintypes.py", line 2, in <module>
    import imp, sys, os
  File "C:\Users\ssarin\Anaconda3\lib\imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by delsim** [comment]
So that warning is arising from some windows-specific functionality that in turn is being loaded by some modules that are being loaded by Dash - its not coming from `django-plotly-dash`.

As a first step, I would check that python and Dash are correctly installed, and then try importing each of the packages in turn directly from a python REPL prompt.

**Comment by samarthsarin** [comment]
Hi,

Thank you for the response. Everything independently seems to be working
fine and imports are successful. I have tried it on different machines as
well as re installing almost all libraries again. Still the same error
persists.

**Comment by delsim** [comment]
Can you do the following:

1. launch python
2. enter `import django` and press return
3. enter ``django.__version__`` and press return
2. enter `import dash` and press return
3. enter ``dash.__version__`` and press return

and then report what responses you get for each step?
