### ISSUE TITLE
Media files don't serve properly with DPD when in DEV mode

### ISSUE THREAD

**Issue by eddy-ojb** [GibbsConsulting/django-plotly-dash#62]
If I have media files that I wish to access, DPD appears to get hold of this request and doesn't play nicely with it:

```
Traceback (most recent call last):
  File "C:\Users\eburm\AppData\Local\conda\conda\envs\platform\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\eburm\AppData\Local\conda\conda\envs\platform\lib\site-packages\django_plotly_dash\middleware.py", line 73, in __call__
    response = request.dpd_content_handler.adjust_response(response)
  File "C:\Users\eburm\AppData\Local\conda\conda\envs\platform\lib\site-packages\django_plotly_dash\middleware.py", line 45, in adjust_response
    c1 = self._replace(response.content,
  File "C:\Users\eburm\AppData\Local\conda\conda\envs\platform\lib\site-packages\django\http\response.py", line 366, in content
    "`streaming_content` instead." % self.__class__.__name__
AttributeError: This FileResponse instance has no `content` attribute. Use `streaming_content` instead.
HTTP GET /media/app_thumbnails/media_9f2MF6K.jpg 500 [0.11, 127.0.0.1:51234]
```

If I remove DPD from the project, the link works fine.

**Comment by eddy-ojb** [comment]
It seems that catching the AttributeError in the `adjust_response` function in the middleware and passing the response on resolves the issue.

I guess this is because DPD's middleware is called before Django's static files app serves the media file and is trying to adjust an inapplicable file.

Would you be satisfied by a pull request with a simple try and except AttributeError code? Changing the code to use 'streaming_content' as per Django's error message broke DPD for me..

**Comment by GibbsConsulting** [comment]
For sure - pull requests most welcome. I thought at the time of writing the middleware that it would be good for any relevant template tag to set some state on the request/response so that the middleware only tries to work when needed, which would be more efficient overall, but treating 'error as cannot replace' as another form of unable to make any substitution is an excellent fix IMHO.
